In [0]:
import tensorflow as tf

In [21]:
print( tf.add( 1, 2 ) )
print( tf.add( [ 1, 2 ] , [ 3, 4 ] ) )
print( tf.square( 5 ) )
print( tf.reduce_sum( [ 1, 2, 3 ] ) ) 

print( tf.square( 2 ) + tf.square( 3 ) )

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(13, shape=(), dtype=int32)


In [22]:
x = tf.matmul( [ [ 1 ] ], [ [ 2, 3 ] ] )
print( x )
print( x.shape )
print( x.dtype )

tf.Tensor([[2 3]], shape=(1, 2), dtype=int32)
(1, 2)
<dtype: 'int32'>


In [23]:
import numpy as np

ndarray = np.ones( [ 3, 3 ] )
print( ndarray )
tensor = tf.multiply( ndarray, 42 )
print( tensor )
print( " Aumenta en 1 " )
print( np.add( tensor, 1 ) )
print( " Tensor convertido en Numpy " )
print( tensor.numpy() )

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)
 Aumenta en 1 
[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]]
 Tensor convertido en Numpy 
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]]


### **Aceleracion de GPU**

In [24]:
x = tf.random.uniform( [ 3, 3 ] )

print( " Is there a GPU available: " )
print( tf.config.experimental.list_physical_devices("GPU") )

print( " Is the Tensor on GPU #0:  " )
print( x.device.endswith('GPU:0') )

 Is there a GPU available: 
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
 Is the Tensor on GPU #0:  
True


In [25]:
import time

def time_matmul( x ):
  start = time.time()
  for loop in range( 10 ):
    tf.matmul( x, x )
  result = time.time() - start
  print( " 10 loop: {:0.2f} ".format( 1000 * result ) )

#Force execution on CPU
print( " On CPU: " )
with tf.device("CPU:0"):
  x = tf.random.uniform( [ 1000, 1000 ] )
  assert x.device.endswith("CPU:0")
  time_matmul( x )

#Force execution on GPU if avalable
if tf.config.experimental.list_physical_devices("GPU"):
  print(" On GPU: ")
  with tf.device("GPU:0"):
    x = tf.random.uniform( [ 1000, 1000 ] )
    assert x.device.endswith("GPU:0")
    time_matmul( x )

 On CPU: 
 10 loop: 171.38 
 On GPU: 
 10 loop: 0.72 


### **dataSet**

In [0]:
ds_tensors = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5, 6])

# Create a CSV file
import tempfile
_, filename = tempfile.mkstemp()

with open(filename, 'w') as f:
  f.write("""Line 1
Line 2
Line 3
  """)

ds_file = tf.data.TextLineDataset(filename)

In [29]:
ds_tensors = ds_tensors.map(tf.square).shuffle(2).batch(2)
print(ds_tensors)

ds_file = ds_file.batch(2)
print(ds_file)

<BatchDataset shapes: (None, None), types: tf.int32>
<BatchDataset shapes: (None, None), types: tf.string>


In [28]:
print('Elements of ds_tensors:')
for x in ds_tensors:
  print(x)

print('\nElements in ds_file:')
for x in ds_file:
  print(x)

Elements of ds_tensors:
tf.Tensor([4 1], shape=(2,), dtype=int32)
tf.Tensor([ 9 25], shape=(2,), dtype=int32)
tf.Tensor([36 16], shape=(2,), dtype=int32)

Elements in ds_file:
tf.Tensor([b'Line 1' b'Line 2'], shape=(2,), dtype=string)
tf.Tensor([b'Line 3' b'  '], shape=(2,), dtype=string)
