In [1]:
import random
from google.colab import drive
drive.mount( '/content/drive' )

Mounted at /content/drive


In [28]:
import numpy as np

class graph_ma:
  def __init__( self ):
    self.matrix = None
    self.poblation = None
    self.solution = None
    self.nVertex = None
    self.nPoblation = None
    self.generation = None

  def viewMatrix( self ):
    for edge in self.matrix:
      if 1 in edge:
        print( edge )

  # Load edge datas
  def readData( self, path ):
    with open( path, 'r' ) as f:
      line = f.readline()
      self.nVertex = int( line.split(' ')[2] ) + int( line.split(' ')[3] )
      self.matrix = np.zeros( ( (self.nVertex - 1) , (self.nVertex - 1) ) )
      line = f.readline()
      while line != '':
        edge = line.split( ' ' )
        self.matrix[ int(edge[1]) - 1 ][ int(edge[2]) - 1 ] = 1
        self.matrix[ int(edge[2]) - 1 ][ int(edge[1]) - 1 ] = 1
        line = f.readline()
    f.close()

  #Solucion inicial
  def initSolution( self, valCol ):
    self.nPoblation = random.randint( 2, random.randint( 2, 10 ) )
    self.solution = np.random.randint( valCol, size = self.nVertex ) 
    for _ in range( self.nPoblation - 1 ):
      self.solution = np.vstack( [ self.solution,  np.random.randint( valCol, size = self.nVertex ) ] )



In [29]:
test = graph_ma()
test.readData( '/content/drive/My Drive/Investigacion y Proyecto de Extension/DataSets/Graphs/DSJC125_1.txt' )
test.initSolution( 6 )



[[5 5 4 ... 4 3 4]
 [0 0 5 ... 4 3 5]
 [2 0 2 ... 2 4 5]
 [2 3 1 ... 0 0 0]]
<class 'numpy.ndarray'>
[5 5 4 0 4 5 4 0 4 4 1 1 5 5 5 4 3 2 3 0 1 3 0 4 3 3 0 0 5 1 2 1 1 5 4 3 4
 1 1 0 0 5 3 0 0 1 2 0 5 4 2 1 1 1 1 1 0 5 4 3 1 0 0 2 4 1 2 3 2 4 0 5 2 2
 1 1 4 0 2 3 1 3 3 0 1 2 0 2 4 4 3 1 4 1 4 2 1 2 1 5 5 0 5 4 5 3 4 1 2 2 2
 0 1 3 1 5 1 3 2 0 3 3 1 2 3 2 3 3 4 5 2 5 4 5 1 0 0 5 4 2 4 3 0 2 1 5 3 1
 2 4 0 1 4 1 0 4 0 2 5 0 5 0 4 1 1 0 5 1 1 2 2 4 2 5 1 3 3 3 5 1 2 3 1 2 5
 3 2 3 3 3 2 5 3 3 1 5 5 0 1 3 1 4 5 1 2 5 4 0 4 3 1 5 5 4 0 0 5 3 3 1 1 2
 1 1 2 2 0 1 2 5 3 0 3 5 4 3 3 0 2 5 2 4 0 5 1 5 1 0 1 0 2 4 4 3 5 1 4 4 0
 4 4 5 0 3 0 2 2 0 0 2 4 4 0 2 1 4 4 3 1 0 2 5 0 2 2 3 5 3 5 1 3 2 4 5 5 0
 2 4 0 1 0 5 1 0 3 0 2 3 1 2 1 3 3 4 4 4 0 5 5 4 2 0 2 2 0 5 0 5 1 0 4 5 0
 3 5 2 0 1 0 4 3 0 1 4 2 3 4 5 5 5 4 3 3 5 1 3 4 1 2 2 1 2 4 2 5 2 3 1 1 1
 3 3 2 5 3 4 5 2 2 4 5 1 3 1 5 3 2 4 1 1 3 1 4 3 0 5 3 3 1 4 3 0 3 4 2 3 5
 2 2 0 5 1 4 0 5 5 5 0 3 0 3 5 4 5 4 2 0 2 3 2 3 5 3 2 0 1 0 4 4 4 4 4 4 0