In [0]:
!pip install h5py

In [0]:
import pandas as pd
import numpy as np
import gzip
import pickle
from google.colab import drive

drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [2]:
from keras.utils import np_utils
from keras.applications.vgg16 import preprocess_input
from keras.applications.vgg16 import VGG16
from keras.models import Sequential
from keras.layers import Dense,Dropout,Embedding
from keras.optimizers import SGD, adam

X_train, y_train = list(),list()

f = gzip.open("/content/drive/My Drive/Colab Notebooks/TPFinal/X_train-5.pkl.gz", 'rb')
varxtrain = pickle.load(f)
f.close()

f = gzip.open("/content/drive/My Drive/Colab Notebooks/TPFinal/y_train.pkl.gz", 'rb')
y_train = pickle.load(f)
f.close()

  
X_train = np.array(varxtrain, dtype = 'float32')
y_train = np.array( y_train, dtype='int16' )

print(X_train.shape)
print(y_train.shape)

Using TensorFlow backend.


NameError: ignored

In [0]:

vgg16 = VGG16(include_top=False, input_shape=(48, 48, 3), weights='imagenet')

def get_vgg16_output(vgg16, array_input, n_feature_maps):
  vg_input = array_input
  picture_train_features = vgg16.predict(vg_input)
  del (vg_input)
  feature_map = np.empty([n_feature_maps, 512])
  for idx_pic, picture in enumerate(picture_train_features):
      feature_map[idx_pic] = picture
  return feature_map

x_train_feature_map = get_vgg16_output(vgg16, varxtrain, len(varxtrain) )
print(x_train_feature_map.shape)

W0621 21:20:20.950232 140397822097280 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0621 21:20:20.994559 140397822097280 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0621 21:20:21.001441 140397822097280 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0621 21:20:21.041008 140397822097280 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:3976: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.



58892288/58889256 [==============================] - 1s 0us/step


W0621 21:20:22.685146 140397822097280 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:174: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.

W0621 21:20:22.686363 140397822097280 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:181: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.



(1308, 512)


In [3]:
#Modelo

topLayerModel = Sequential()
topLayerModel.add(Dense(256, input_shape=(512,), activation='relu'))
topLayerModel.add(Dense(256, input_shape=(256,), activation='relu'))
topLayerModel.add(Dropout(0.5))
topLayerModel.add(Dense(128, input_shape=(256,), activation='relu'))
topLayerModel.add(Dense(7, activation='softmax'))

topLayerModel.summary()
adamax = adam()
topLayerModel.compile(loss='categorical_crossentropy',optimizer=adamax, metrics=['accuracy'])
topLayerModel.fit(x_train_feature_map, y_train, validation_data=(x_train_feature_map, y_train),epochs=35, batch_size= 1)   

W0623 23:09:26.861540 140621223552896 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0623 23:09:26.901838 140621223552896 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0623 23:09:26.907737 140621223552896 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0623 23:09:26.935069 140621223552896 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:133: The name tf.placeholder_with_default is deprecated. Please use tf.compat.v1.placeholder_with_default instead.

W0623 23:09:26.944416 

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 256)               131328    
_________________________________________________________________
dense_2 (Dense)              (None, 256)               65792     
_________________________________________________________________
dropout_1 (Dropout)          (None, 256)               0         
_________________________________________________________________
dense_3 (Dense)              (None, 128)               32896     
_________________________________________________________________
dense_4 (Dense)              (None, 7)                 903       
Total params: 230,919
Trainable params: 230,919
Non-trainable params: 0
_________________________________________________________________


NameError: ignored

In [0]:
import gzip
import pickle

X_test, y_test = list(),list()

f = gzip.open("/content/drive/My Drive/Colab Notebooks/TPFinal/X_test-5.pkl.gz", 'rb')
varxtest = pickle.load(f)
f.close()

f = gzip.open("/content/drive/My Drive/Colab Notebooks/TPFinal/y_test.pkl.gz", 'rb')
y_test = pickle.load(f)
f.close()
  
X_test = np.array(varxtest, dtype = 'float32')
y_test = np.array( y_test, dtype='int16' )

print(X_test.shape)
print(y_test.shape)

x_test_feature_map = get_vgg16_output(vgg16, varxtest, len(varxtest) )


(327, 48, 48, 3)
(327, 7)


In [0]:
scores = topLayerModel.evaluate( x_test_feature_map,y_test)
print("\n%s: %.2f%%" %( topLayerModel.metrics_names[1], scores[1] * 100 ) )
print(topLayerModel.metrics_names)
print(scores)

327/327 [==============================] - 0s 71us/step

acc: 97.55%
['loss', 'acc']
[0.06586956743162342, 0.9755351683779958]


In [0]:
y_pred = topLayerModel.predict_classes(x_test_feature_map)
print(x_test_feature_map.shape)

y_classes = [np.argmax(y, axis=None, out=None) for y in y_test] #Nos permite volver a ver el valor numerico y no categorico

numero_columnas = numero_filas = 7
matriz = [[0] * numero_columnas for i in range(numero_filas)]
matriz = np.array(matriz)
for k in range( len(y_pred) ):
  matriz[int(y_classes[k])][int(y_pred[k])] += 1 #fila valor real columna prediccion
print(matriz)
print ("Precision: " + str( float ( np.trace(np.array(matriz)) ) / len(y_pred) ))


(327, 512)
[[43  0  1  0  0  1  0]
 [ 0 18  0  0  0  0  0]
 [ 0  0 57  0  0  2  0]
 [ 0  0  0 24  1  0  0]
 [ 0  0  0  0 69  0  0]
 [ 1  0  0  0  0 27  0]
 [ 0  0  1  0  1  0 81]]
Precision: 0.9755351681957186


In [0]:
from keras.models import model_from_json
model_json = topLayerModel.to_json()
with open("model.json", "w") as json_file:
  json_file.write(model_json)
#serializan los pesos (weights) para HDF5
topLayerModel.save_weights("model.h5")
print("Modelo guardado en el PC")
# despues...
# carga el json y crea el modelo
json_file = open('model.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)
# se cargan los pesos (weights) en el nuevo modelo
loaded_model.load_weights("model.h5")
print("Modelo cargado desde el PC")
# se evalua el modelo cargado con los datos de los test
loaded_model.compile(loss='categorical_crossentropy',optimizer=adamax, metrics=['accuracy'])

score = loaded_model.evaluate(x_test_feature_map, y_test, verbose=0)
print("%s: %.2f%%" % (loaded_model.metrics_names[1], score[1]*100))

In [0]:
pred = loaded_model.predict_classes(x_test_feature_map)
numero_columnas = numero_filas = 7
confusion = [[0] * numero_columnas for i in range(numero_filas)]
confusion = np.array(confusion)
for k in range( len(y_pred) ):
  confusion[int(y_classes[k])][int(pred[k])] += 1 #fila valor real columna prediccion
print(confusion)
print ("Precision: " + str( float ( np.trace(np.array(confusion)) ) / len(pred) ))