**Cantidad de Imagenes:**
1.   0 - 180
2.   1 - 72
3.   2 - 236
4.   3 - 100 
5.   4 - 276
6.   5 - 112
7.   6 - 332

Total 1308 imagenes de entrenamiento
 y 327 para pruebas

Tomando las ultimas 5 imagenes de cada carpeta de las cuales 4 son para entrenamiento y 1 de prueba

Modulo import image2feature

Este modulo nos permite importar  image2feature.py

In [0]:

from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive/My\ Drive/Colab Notebooks/TPFinal

# List files to make sure we're in the expected directory.
# Your output will look different, showing your own Drive files here.
!ls
!ls -l image2feature.py

import image2feature as i2f


Modulo de Generacion: X_train

In [0]:

import numpy as np
import cv2
import re
from pathlib import Path
from keras.utils import np_utils
import pickle
import gc 
import gzip


def ls(ruta = Path.cwd()):
    return [arch.name for arch in Path(ruta).iterdir() if arch.is_file()]

count = 0
X_train = list()
with open("/content/drive/My Drive/Colab Notebooks/TPFinal/dataset.txt","r") as file:
    line = file.readline()
    #while ( (int) (line[9:]) != 6 ):
    #  line = file.readline()
    while ( line != '' and (int) (line[9:]) < 7 ):
        #preproc = i2f.Extractor()
        ruta  = "/content/drive/My Drive/Cohn-kanade-dataset/"+str(line[:4])+'/'+str(line[5:8])+'/'
        lista = ls( ruta )
        for i in range(len(lista)-3 , len(lista) ):
          if( i != len(lista)-1 ):       
            count += 1
            #X_train.append( preproc.extract( cv2.imread( ruta + lista[i] ) ) )
        line = file.readline()

print(count)
#with gzip.open("/content/drive/My Drive/Colab Notebooks/TPFinal/x_trainp6.pkl.gz","wb") as of:
#	pickle.dump((np.array(X_train)),of, pickle.HIGHEST_PROTOCOL)

#gc.collect()


654


Modulo de generacion: y_train

In [0]:

import numpy as np
import cv2
import re
from pathlib import Path
from keras.utils import np_utils
import pickle
import gzip


def ls(ruta = Path.cwd()):
    return [arch.name for arch in Path(ruta).iterdir() if arch.is_file()]

y_train = list()
with open("/content/drive/My Drive/Colab Notebooks/TPFinal/dataset.txt","r") as file:
    line = file.readline()
    while ( line != '' ):
        ruta  = "/content/drive/My Drive/Cohn-kanade-dataset/"+str(line[:4])+'/'+str(line[5:8])+'/'
        lista = ls( ruta )
        for i in range(len(lista)-3 , len(lista) ):
          if( i != len(lista)-1 ):       
            y_train.append( (int) (line[9:]) )
        line = file.readline()
        
with gzip.open("/content/drive/My Drive/Colab Notebooks/TPFinal/y_trainp.pkl.gz","wb") as of:
	pickle.dump(np_utils.to_categorical(y_train),of, pickle.HIGHEST_PROTOCOL)


Modulo de Generacion: X_test 

In [0]:
import numpy as np
import cv2
import re
from pathlib import Path
from keras.utils import np_utils
import pickle
import gzip


def ls(ruta = Path.cwd()):
    return [arch.name for arch in Path(ruta).iterdir() if arch.is_file()]

X_test = list()
with open("/content/drive/My Drive/Colab Notebooks/TPFinal/dataset.txt","r") as file:
    line = file.readline()
    while ( line != '' and (int) (line[9:]) < 4):
      preproc = i2f.Extractor()
      ruta  = "/content/drive/My Drive/Cohn-kanade-dataset/"+str(line[:4])+'/'+str(line[5:8])+'/'
      lista = ls( ruta )
      X_test.append( preproc.extract( cv2.imread( ruta + lista[ len(lista) - 1 ] ) ) ) 
      line = file.readline()

with gzip.open("/content/drive/My Drive/Colab Notebooks/TPFinal/test0-3.pkl.gz","wb") as of:
	pickle.dump(np.array(X_test),of, pickle.HIGHEST_PROTOCOL)


In [0]:

import numpy as np
import cv2
import re
from pathlib import Path
from keras.utils import np_utils
import pickle
import gzip


def ls(ruta = Path.cwd()):
    return [arch.name for arch in Path(ruta).iterdir() if arch.is_file()]

X_test = list()
with open("/content/drive/My Drive/Colab Notebooks/TPFinal/dataset.txt","r") as file:
    line = file.readline()
    while ( line != '' ):
      while( (int) (line[9:]) < 4 ):
        line = file.readline()
      preproc = i2f.Extractor()
      ruta  = "/content/drive/My Drive/Cohn-kanade-dataset/"+str(line[:4])+'/'+str(line[5:8])+'/'
      lista = ls( ruta )
      X_test.append( preproc.extract( cv2.imread( ruta + lista[ len(lista) - 1 ] ) ) ) 
      line = file.readline()

with gzip.open("/content/drive/My Drive/Colab Notebooks/TPFinal/test4-6.pkl.gz","wb") as of:
	pickle.dump(np.array(X_test),of, pickle.HIGHEST_PROTOCOL)



Modulo de Generacion:  y_test

In [0]:

import numpy as np
import cv2
import re
from pathlib import Path
from keras.utils import np_utils
import pickle
import gzip


def ls(ruta = Path.cwd()):
    return [arch.name for arch in Path(ruta).iterdir() if arch.is_file()]

y_test = list()
with open("/content/drive/My Drive/Colab Notebooks/TPFinal/dataset.txt","r") as file:
    line = file.readline()
    while ( line != '' ):
      ruta  = "/content/drive/My Drive/Cohn-kanade-dataset/"+str(line[:4])+'/'+str(line[5:8])+'/'
      lista = ls( ruta )
      y_test.append( (int) (line[9:]) ) 
      line = file.readline()

with gzip.open("/content/drive/My Drive/Colab Notebooks/TPFinal/y_test.pkl.gz","wb") as of:
	pickle.dump(np_utils.to_categorical(y_test),of, pickle.HIGHEST_PROTOCOL)
  

Modulo de carga X_train e y_train

In [1]:
from google.colab import drive
import pickle
import numpy as np
import gzip

drive.mount('/content/drive')

f = gzip.open("/content/drive/My Drive/Colab Notebooks/TPFinal/Pruebas/X_train0.pkl.gz", 'rb')
X_train = pickle.load(f)
f.close() 

for i in range(1,7):
  f = gzip.open("/content/drive/My Drive/Colab Notebooks/TPFinal/Pruebas/X_train"+str(i)+".pkl.gz", 'rb')
  X_train = np.concatenate( ( X_train, pickle.load(f) ) )
  f.close()

#f = gzip.open("/content/drive/My Drive/Colab Notebooks/TPFinal/x_trainp0-2.pkl.gz", 'rb')
#X_train = pickle.load(f)
#f.close()
  
#f = gzip.open("/content/drive/My Drive/Colab Notebooks/TPFinal/x_trainp2-4.pkl.gz", 'rb')
#X_train = np.concatenate( ( X_train, pickle.load(f) ) )
#f.close()
  
#f = gzip.open("/content/drive/My Drive/Colab Notebooks/TPFinal/x_trainp4-5.pkl.gz", 'rb')
#X_train = np.concatenate( ( X_train, pickle.load(f) ) )
#f.close()

#f = gzip.open("/content/drive/My Drive/Colab Notebooks/TPFinal/x_trainp6.pkl.gz", 'rb')
#X_train = np.concatenate( ( X_train, pickle.load(f) ) )
#f.close()

f = gzip.open("/content/drive/My Drive/Colab Notebooks/TPFinal/y_train.pkl.gz", 'rb')
y_train = pickle.load(f)
f.close() 

print( X_train.shape )
print( y_train.shape )
print(y_train)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
(1308, 25088)
(1308, 7)
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


Modelo IA

In [3]:

from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD, adam

X_train = np.array( X_train, dtype = 'float32'  )
X_train /= np.amax( X_train, axis = 0 )
y_train = np.array( y_train, dtype = 'int16')

print(X_train.shape)
print(y_train.shape)

model = Sequential()
model.add( Dense( 10000, input_dim = 25088, activation = 'relu' ) )
model.add( Dense( 8000, activation = 'relu' ) )
model.add( Dense( 6000, activation = 'relu' ) )
model.add( Dense( 2000, activation = 'relu' ) )
model.add( Dense( 500, activation = 'relu' ) )
model.add( Dense( 7, activation = 'sigmoid' ) )


epocas = 15
lrate = 0.01
decay = lrate/epocas

sgd = SGD( lr = lrate, momentum = 0.9, decay = decay, nesterov = False )

model.compile( loss = 'categorical_crossentropy', optimizer = sgd , metrics=['accuracy'] )
model.summary()
model.fit(X_train, y_train, epochs=epocas, batch_size = 20 )



(1308, 25088)
(1308, 7)
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_7 (Dense)              (None, 10000)             250890000 
_________________________________________________________________
dense_8 (Dense)              (None, 8000)              80008000  
_________________________________________________________________
dense_9 (Dense)              (None, 6000)              48006000  
_________________________________________________________________
dense_10 (Dense)             (None, 2000)              12002000  
_________________________________________________________________
dense_11 (Dense)             (None, 500)               1000500   
_________________________________________________________________
dense_12 (Dense)             (None, 7)                 3507      
Total params: 391,910,007
Trainable params: 391,910,007
Non-trainable params: 0
______________________________________

Todas las MPL propuesta con datos normalizados siempre dan 0.2538

```
model = Sequential()
model.add( Dense( 10000, input_dim = 25088, activation = 'relu' ) )
model.add( Dense( 8000, activation = 'relu' ) )
model.add( Dense( 6000, activation = 'relu' ) )
model.add( Dense( 2000, activation = 'relu' ) )
model.add( Dense( 500, activation = 'relu' ) )
model.add( Dense( 7, activation = 'sigmoid' ) )

epocas = 10
lrate = 0.01
```

```
model.add( Dense( 10000, input_dim = 25088, activation = 'relu' ) )
model.add( Dense( 5000, activation = 'relu' ) )
model.add( Dense( 1500, activation = 'relu' ) )
model.add( Dense( 500, activation = 'relu' ) )
model.add( Dense( 50, activation = 'relu' ) )
model.add( Dense( 7, activation = 'sigmoid' ) )
```
```
model.add( Dense( 12000, input_dim = 25088, activation = 'relu' ) )
model.add( Dense( 6000, activation = 'relu' ) )
model.add( Dense( 500, activation = 'relu' ) )
model.add( Dense( 50, activation = 'relu' ) )
model.add( Dense( 7, activation = 'sigmoid' ) )
```


Eliminaciones de Variables

In [0]:
del X_train
del y_train

Modulo de carga X_test e y_test

In [5]:
from google.colab import drive
import pickle
import numpy as np
import gzip

drive.mount('/content/drive')

f = gzip.open("/content/drive/My Drive/Colab Notebooks/TPFinal/Pruebas/test0-3.pkl.gz", 'rb')
X_test = pickle.load(f)
f.close() 

f = gzip.open("/content/drive/My Drive/Colab Notebooks/TPFinal/Pruebas/test4-6.pkl.gz", 'rb')
X_test = np.concatenate( ( X_test, pickle.load(f) ) )
f.close()

f = gzip.open("/content/drive/My Drive/Colab Notebooks/TPFinal/y_test.pkl.gz", 'rb')
y_test = pickle.load(f)
f.close() 

print( len(X_test) )
print( len(y_test) )

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
327
327


Prueba IA

In [7]:
import sklearn.metrics as metrics

X_train = np.array( X_train, dtype = 'float32'  )
X_train /= np.amax( X_train, axis = 0 )
y_train = np.array( y_train, dtype = 'int16')

scores = model.evaluate( X_test, y_test )
print("\n%s: %.2f%%" %( model.metrics_names[1], scores[1] * 100 ) )
#for i in model.predict_on_batch(X_test):
#  print(i)

327/327 [==============================] - 0s 486us/step

acc: 25.38%


In [10]:
y_pred = model.predict_classes ( X_test )
print( X_test.shape )

#Nos permite volver a ver el valor numerico perteneciente a la categoria correspondiente
y_classes = [ np.argmax( y, axis=None, out=None ) for y in y_test ] 

n_columns = n_row = 7
matrix = [ [0] * n_columns for i in range(n_row) ]
matrix = np.array( matrix )
for k in range( len( y_pred ) ):
  matrix[ int(y_classes[k]) ][ int(y_pred[k]) ] += 1 
print( matrix )
print ( "Precision: " + str( float( np.trace( np.array( matrix ) ) ) / len(y_pred) ) )

(327, 25088)
[[ 0  0  0  0  0  0 45]
 [ 0  0  0  0  0  0 18]
 [ 0  0  0  0  0  0 59]
 [ 0  0  0  0  0  0 25]
 [ 0  0  0  0  0  0 69]
 [ 0  0  0  0  0  0 28]
 [ 0  0  0  0  0  0 83]]
Precision: 0.25382262996941896


Eliminacion de Test

In [0]:
del X_test
del y_test