0 - 180
1 - 72
2 - 236
3 - 100 
4 - 276
5 - 112
6 - 332

In [1]:
from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive/My\ Drive/TPFinal

# List files to make sure we're in the expected directory.
# Your output will look different, showing your own Drive files here.
!ls
!ls -l image2feature.py

import image2feature as i2f

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/My Drive/TPFinal
'Copia de EmocionesAna.ipynb'   image2feature.py	 X_train0.pkl.gz
 dataset.py		        image2feature.pyc	 X_train2.pkl.gz
 dataset.txt		        ImportarArchivos.ipynb	 X_train4.pkl.gz
 EmocionesAna.ipynb	        __pycache__		 X_train6.pkl.gz
 EmocionesWalter.ipynb	        test0-3.pkl.gz		 y_train.pkl.gz
-rw------- 1 root root 896 Jun 13 14:30 image2feature.py


Using TensorFlow backend.


In [0]:
from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive/My\ Drive/TPFinal

# List files to make sure we're in the expected directory.
# Your output will look different, showing your own Drive files here.
#!ls
!ls -l image2feature.py

import image2feature as i2f
import numpy as np
import cv2
import re
from pathlib import Path
from keras.utils import np_utils
import pickle
import gc
import gzip


def ls( ruta = Path.cwd() ):
  return [arch.name for arch in Path( ruta ).iterdir() if arch.is_file()]

X_train = list()
with open("/content/drive/My Drive/TPFinal/dataset.txt","r") as file:
  line = file.readline()
  print ( line )
  while( line!='' ):
    if( ( (int) (line[9:]) ==0 ) or ((int) (line[9:]) == 1) or ((int) (line[9:])==2) ):   
      preproc = i2f.Extractor()
      ruta = "/content/drive/My Drive/Cohn-kanade-dataset/"+str(line[:4])+'/'+str(line[5:8])+'/'
      lista = ls( ruta )
      #print(ruta)
      for i in range( len(lista)-5, len(lista) ):
        if( line != len(lista)-1 ):
          X_train.append( preproc.extract( cv2.imread(ruta + lista[i])))
      line = file.readline()
      
with gzip.open("/content/drive/My Drive/TPFinal/X_t.plk.gz","wb") as of:
  pickle.dump(np.array(X_train), of, pickle.HIGHEST_PROTOCOL)
  
gc.collect()
print("fin")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/My Drive/TPFinal
-rw------- 1 root root 896 Jun 13 14:30 image2feature.py


Using TensorFlow backend.
W0615 16:04:36.484181 140673178597248 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0615 16:04:36.562549 140673178597248 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0615 16:04:36.571367 140673178597248 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0615 16:04:36.606682 140673178597248 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:3976: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.



S067 004 0



W0615 16:04:38.970110 140673178597248 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:174: The name tf.get_default_session is deprecated. Please use tf.compat.v1.get_default_session instead.

W0615 16:04:38.972326 140673178597248 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:181: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.



In [1]:
from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive/My\ Drive/TPFinal

# List files to make sure we're in the expected directory.
# Your output will look different, showing your own Drive files here.
#!ls
!ls -l image2feature.py

import image2feature as i2f
import numpy as np
import cv2
import re
from pathlib import Path
from keras.utils import np_utils
import pickle
import gc
import gzip

f = gzip.open("/content/drive/My Drive/TPFinal/X_train1.pkl.gz","rb")
X_train = pickle.load(f)
f.close()
print(X_train)

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive
/content/drive/My Drive/TPFinal
-rw------- 1 root root 896 Jun 13 14:30 image2feature.py


Using TensorFlow backend.


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
